
services:
  backend:
    build:
      context: ./gestion_coffre_backend
      dockerfile: Dockerfile
    env_file:
      - ./gestion_coffre_backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./gestion_coffre_backend:/var/www/html
    depends_on:
      - mysql

  frontend:
    build:
      context: ./gestion-coffre
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./gestion-coffre:/app

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: coffre_db
      MYSQL_USER: coffre_user
      MYSQL_PASSWORD: coffre_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
